const PASSENGER = 1;
const VEHICLE_OWNER =2;
const SUPERVISOR = 3;
const DRIVER = 4
const ADMIN = 420;

//Request Type
VEHICLE_ADDITION_REQUEST=1
WITHDRAW_REQUEST =100
SUPERVISOR_ADDITION_REQUEST = 200
DRIVIER_ADDITION_REQUEST = 300



module.exports = {PASSENGER,VEHICLE_OWNER,SUPERVISOR,ADMIN, DRIVER, VEHICLE_ADDITION_REQUEST, WITHDRAW_REQUEST, SUPERVISOR_ADDITION_REQUEST, DRIVIER_ADDITION_REQUEST}